### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by ldimaggi** [nodeshift-starters/nodejs-istio-routing#9]
The link in the README file - https://github.com/nodeshift-starters/nodejs-istio-routing/blob/master/README.md is broken.

The link is:
https://github.com/openshift-istio/istio-docs/blob/master/user-journey.adoc

Returns a 404 - where was the information in this doc moved?  Thx!

**Comment by ldimaggi** [comment]
IS it here?

https://github.com/openshift-istio/istio-docs/blob/master/content/install-mvp.adoc

**Comment by lholmquist** [comment]
I have a PR, https://github.com/nodeshift-starters/nodejs-istio-routing/pull/8/files, that updates the readme a bit since somethings have changed.  

this might help

**Comment by lholmquist** [comment]
The readme is now updated with that PR i linked before.

Also, i saw that they are updating the "official" instructions with a PR here,  https://github.com/Maistra/maistra.github.io/pull/35
